all: personas.csv papers.csv papersXpersonas.csv

personas.csv:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/congreso/releases/download/comunidad/personas.zip
	unzip personas.zip

papers.csv:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/congreso/releases/download/comunidad/papers.zip
	unzip papers.zip

papersXpersonas.csv:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/congreso/releases/download/comunidad/papersXpersonas.zip
	unzip papersXpersonas.zip
